### ISSUE TITLE
Use ros-bridge to get the information of more than one vehicle

### ISSUE THREAD

**Issue by houssamkanso** [carla-simulator/ros-bridge#105]
Hey,
Is it possible to use ros-bridge to get the data (location, velocity, acceleration ...) of all the vehicles in the simulation in real time ? and how can we do it ?

**Comment by fpasch** [comment]
Please have a look at this branch:
https://github.com/carla-simulator/ros-bridge/tree/feature/odo_for_all
You can get the odometry of all vehicles via topics `/carla/vehicle/<VEHICLE ID>/odometry`.
Is that sufficient for your use case?

**Comment by houssamkanso** [comment]
Thank you i will check this it !! and regarding the information about steering wheel and brakes of all the vehicles ?

**Comment by fatemehprhm** [comment]
Hi, how could you solve this problem? cause the link is un available now.
