### ISSUE TITLE
Adding Vehicle ID to ROS Bridge 

### ISSUE THREAD

**Issue by ignacioalvmar** [carla-simulator/ros-bridge#106]
This is not an issue, it's a feature request.

Could we add Vehicle IDs to the ROS-bridge? 
Both for the ego-vehicle and the npc vehicles.

It would be very useful for displaying the vehicle ids in a similar way than the no-rendering mode.
It can also be useful to perform "per-ID" processing on ROS nodes.

**Comment by fpasch** [comment]
With #112, you get the id of the ego vehicle.
For all vehicles there are two other topics:
- object-sensor-like `/carla/objects`: [ObjectArray](http://docs.ros.org/api/derived_object_msgs/html/msg/ObjectArray.html)
- marker array (e.g. for displaying in rviz) `/carla/vehicle_marker`: [MarkerArray](http://docs.ros.org/api/visualization_msgs/html/msg/MarkerArray.html)
