### ISSUE TITLE
Support ros2

### ISSUE THREAD

**Issue by pprivulet** [carla-simulator/ros-bridge#124]
Hi, Do you have any plan to support ros2?

**Comment by fpasch** [comment]
Some efforts have already been made to separate the communication side. That should simplify adding support for ROS2. But currently, there is no actual schedule for that. 
Would you be able to support this task?

**Comment by pprivulet** [comment]
I would like to try .THX

**Comment by MaskedName** [comment]
Any update on ROS2 support?

**Comment by icaropires** [comment]
Any update?
