### ISSUE TITLE
ROS Bridge dies when creating ego vehicle, attribute error

### ISSUE THREAD

**Issue by chandamarnath** [carla-simulator/ros-bridge#134]
I have installed CARLA 0.9.5 and the ROS Bridge 0.9.5.1. I am running ROS Melodic. I get the ROS bridge startup fine, but on spawning the ego vehicle I get the error:
AttributeError: 'WheelPhysicsControl' object has no attribute 'max_steer_angle'

Any idea what I can do now? Do I revert to CARLA 0.9.4 and the same ROS Bridge?

**Comment by fpasch** [comment]
CARLA 0.9.5 and ROS Bridge 0.9.5.1 should work as expected. Have you ensured, that your environment is clean (i.e. catkin-created directories removed)

**Comment by fpasch** [comment]
resolved by #145
