### ISSUE TITLE
Pedestrian odometry

### ISSUE THREAD

**Issue by javieryu** [carla-simulator/ros-bridge#144]
Is there a way to configure the carla_ros_bridge to publish the pose of pedestrians?

**Comment by fpasch** [comment]
That's not yet possible. But it should be easy to implement.

I would suggest to add the pedestrians to the `/carla/objects` topic.

Here are the steps you have to execute:
1. Create Pedestrian-Class (derive from vehicle.py, similar to ego_vehicle.py.  The interesting part is the `classification` that is read within Vehicle.get_object_info(). Set that to pedestrian. )
2. Similar to [here](https://github.com/carla-simulator/ros-bridge/blob/8069076632c422154193e12973200ad26e9667be/carla_ros_bridge/src/carla_ros_bridge/bridge.py#L310), instantiate the Pedestrian class when `carla_actor.type_id.startswith("walker")`
3. Within [object_sensor.py](https://github.com/carla-simulator/ros-bridge/blob/8069076632c422154193e12973200ad26e9667be/carla_ros_bridge/src/carla_ros_bridge/object_sensor.py#L64) extend the check by: `or isinstanceof(actor, Pedestrian)`

Feel free to send your code as a pull request.
