### ISSUE TITLE
problem with the PythonAPIs (timestamp and wheel)

### ISSUE THREAD

**Issue by Owen-Liuyuxuan** [carla-simulator/ros-bridge#161]
The master version or ros-bridge on 7.18 does not comply with the compiled release of Carla 0.94 and 0.95.
1. 
![Screenshot from 2019-07-18 15-02-37](https://user-images.githubusercontent.com/31618608/61436358-32c7e000-a96d-11e9-82a7-fabd2a4135b2.png)

Based on the pythonAPI of 0.94 and 0.95 carla.timestamed object only have attibute frame_count:
## `carla.Timestamp`

- `frame_count`
- `elapsed_seconds`
- `delta_seconds`
- `platform_timestamp`
- `__eq__(other)`
- `__ne__(other)`

2. 
![Screenshot from 2019-07-18 15-02-50](https://user-images.githubusercontent.com/31618608/61436533-95b97700-a96d-11e9-9316-a2d41bff4a68.png)
Based on the pythonAPI of 0.94 and 0.95 wheel_physics object only have no attibutes on "max_degree":
## `carla.WheelsPhysicsControl`

- `tire_friction`
- `damping_rate`
- `steer_angle`
- `disable_steering`
- `__eq__(other)`
- `__ne__(other)`

**Comment by fpasch** [comment]
That's expected behavior. For older CARLA versions, please use a tagged version of ros-bridge.
