### ISSUE TITLE
Indobund TCP/IP connection failed

### ISSUE THREAD

**Issue by mirkocemes** [carla-simulator/ros-bridge#163]
Hello.
I'am using latest Carla simulator version and latest carla ros bridge version but when I run `roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch`, I get following output:
Inbound TCP/IP connection failed: field frame must be unsigned integer type
So, if someone knows how to fix it, please help me.

**Comment by fpasch** [comment]
Please ensure, that with latest ros-bridge master you need CARLA 0.9.6

**Comment by fpasch** [comment]
Do you still face the issue?

**Comment by Kin-Zhang** [comment]
This problem occur when I do `rosbag record -a`
