### ISSUE TITLE
Issue with ROS not publishing any data. client_with_rviz displaying nothing. 

### ISSUE THREAD

**Issue by NeilNie** [carla-simulator/ros-bridge#17]
Hello!

I am having trouble running `client_with_rviz.launch`. After following the tutorial and running the commands, rviz opens up and nothing shows up. 
![screenshot from 2018-12-25 17-21-22](https://user-images.githubusercontent.com/10865578/50427009-fbc39d00-0869-11e9-8ce5-821cded73e44.png)

Furthermore, it seems like the client has connected to the server. Debugging with ROS shows that there is no data being published under these topics. 
![screenshot from 2018-12-25 17-26-03](https://user-images.githubusercontent.com/10865578/50427013-2c0b3b80-086a-11e9-8da4-39557f1dcb31.png)

Thank you and Merry Christmas!

**Comment by danil-tolkachev** [comment]
You also need to run `manual_control.py` according to the [documentation](https://github.com/carla-simulator/ros-bridge#start-the-ros-bridge).

**Comment by NeilNie** [comment]
Thank you! The issue is resolved!
