### ISSUE TITLE
Add receiver in bridge to enable debug features

### ISSUE THREAD

**Issue by cmpute** [carla-simulator/ros-bridge#173]
Could you add some feature to receive ROS messages and display them in Carla? Specifically display visualization_msgs/Marker and visualization_msgs/MarkerArray in Carla spectator. [Several marker primitives](http://wiki.ros.org/rviz/DisplayTypes/Marker) are already in the debug helper function: draw_line, draw_arrow, draw_text, draw_box.

Additionally, is there any approach to display text from draw_text in rviz? I noticed that the documentation said that the text is only visible in server side, however I found a class called spectator in the ros_bridge package.

**Comment by fpasch** [comment]
Could you please give pull request #176 a try and comment if it's working for you?

**Comment by cmpute** [comment]
Cool! I tested it and it works now! Thanks a lot!

**Comment by cmpute** [comment]
I found a small bug. It seems that the y coordinate is not converted back to CARLA system (no negative sign is added for y values). Thus the result boxes and arrows shown in CARLA is opposite

**Comment by cmpute** [comment]
Another problem is that does Carla support delete existing debug elements? I use similar approach as yours to create markers, however it seems that Marker.MODIFY and Marker.DELETE are not actually supported.

**Comment by fpasch** [comment]
You're warmly welcome to contribute. Would you be able to send a fix for the Carla coordinate conversion?

Regarding the removal of debug markers:
It seems not to be supported by CARLA itself. Please file an issue there addressing this feature.
