### ISSUE TITLE
[Question] How to add controllable pedestrians?

### ISSUE THREAD

**Issue by bbrito** [carla-simulator/ros-bridge#208]
I notice that in the in carla 0.9.6 we can add and control pedestrians. How can you do it through the ROS bridge?

Thank you for your help.

**Comment by fpasch** [comment]
There is currently no ROS node to spawn pedestrians. So you need to create your own Carla-python-client to spawn it.

Afterwards ROS-bridge should provide an interface to control it via ROS topics: [documentation](https://github.com/carla-simulator/ros-bridge#walker)

**Comment by bbrito** [comment]
Ok. I adapted the bridge to spawn pedestrians according to with the config file. I will send a pull request in case you want to take it into account.
