### ISSUE TITLE
Low publishing rate of image data

### ISSUE THREAD

**Issue by Canorvantis** [carla-simulator/ros-bridge#234]
I am using CARLA ROS Bridge in combination with the manual control script from CARLA. It works fine, but the publishing rate of images in /carla/hero/camera/rgb/front/image_color is just around 8-10 FPS (measured with rostopic hz), while the game window shows a framerate around 60. Is there any way to get highter FPS in the ROS Topic?

Thanks

**Comment by fpasch** [comment]
Could you please check the behavior with carla_manual_control+carla_ego_vehicle from this repo?

**Comment by fpasch** [comment]
As there was no answer, I'll close this issue.
