### ISSUE TITLE
roslaunch stuck at 'Created Trafficlight'

### ISSUE THREAD

**Issue by jasonxzzhang** [carla-simulator/ros-bridge#244]
Hi,

I managed to use the apt-get install to install 'carla 0.9.8' and 'carla-ros-bridge-melodic' following the instructions on 0.9.8 release page. However when I execute `roslaunch carla_ros_bridge carla_ros_bridge.launch` 

the terminal stuck at the 'created trafficlight' stage as shown below

![Screenshot from 2020-03-16 12-41-57](https://user-images.githubusercontent.com/56538409/76759570-d7f8b980-6783-11ea-8784-e101df53c719.png)

the Carla server is running normally, please advise me on how to solve this, thanks.

**Comment by fpasch** [comment]
That might not necessarily be an issue (it might be simply the last element that was found).
Are there any topics, that are not getting published?
