### ISSUE TITLE
Error when using ros bridge with carla 0.9.8

### ISSUE THREAD

**Issue by mostafaayman17037** [carla-simulator/ros-bridge#251]
![image](https://user-images.githubusercontent.com/43115678/77709794-d7a6bc80-6fd4-11ea-9d0c-540f60dc8e0f.png)
when i launch this launch file ( carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch )i keep finding this error , i hope any one can help me in solving this issue

**Comment by fpasch** [comment]
please update the carla_msgs submodule

    git submodule update --init
