### ISSUE TITLE
I have a problem when launching  roslaunch carla_ros_bridge carla_ros_bridge_with_ego_vehicle_example.launch gives me the following error  undefined symbol: PyUnicodeUCS4_FromEncodedObject

### ISSUE THREAD

**Issue by zeyadtahoon** [carla-simulator/ros-bridge#254]
I have tried to re-install carla ros bridge and also carla itself but nothing works 
I export the .egg file but there is also a problem when 
         python -c 'import carla;print("Success")'
  
![Screenshot from 2020-03-27 18-54-41](https://user-images.githubusercontent.com/60602074/77780384-922dd200-705c-11ea-9043-df695cc65bc2.png)

![Screenshot from 2020-03-27 18-50-58](https://user-images.githubusercontent.com/60602074/77780100-251a3c80-705c-11ea-9920-9e4833836013.png)

**Comment by fpasch** [comment]
It seems, your python environment is messed up. Please try on a clean ubuntu 16.04 or 18.04 installation.
