### ISSUE TITLE
Test Ackermann control messages have no effect

### ISSUE THREAD

**Issue by ruixuanz** [carla-simulator/ros-bridge#257]
Hi,

I'm experiencing difficulties with test control commands. I spanned a "hero" vehicle by using manual_control.py and launched the bridge ros package. I'm able to echo the topics posted by the bridge, but publishing to the /carla/ego_vehicle/ackermann_cmd topic doesn't do anything - the car only reacts to the keyboard.
I tried removing everything related to the keyboard in the manual_control.py but no luck - the ackermann_cmd still doesn't do anything.

Let me know what might be the problem.

______________________________________________________________________________________
I have the same problem with the above one but due to some reason the original post was closed and I can not find the solution to this issue. Can anybody give me some hints about it? Thank you!

**Comment by fpasch** [comment]
You cannot use manual_control.py as it overwrites the control commands.
Please use the ROS node [carla_ego_vehicle](https://github.com/carla-simulator/ros-bridge/tree/master/carla_ego_vehicle) to spawn and [carla_manual_control](https://github.com/carla-simulator/ros-bridge/tree/master/carla_manual_control) to control the ego vehicle. You should also be able to use the [ackermann_control](https://github.com/carla-simulator/ros-bridge/tree/master/carla_ackermann_control) node then.

You can then also control the car manually:  press 'b' within carla_manual_control pygame window to override the vehicle controls.
