### ISSUE TITLE
Error when launching carla ros bridge using source repository

### ISSUE THREAD

**Issue by arstek131** [carla-simulator/ros-bridge#259]
Following Carla doc I used option B (using source repositry, because I need to edit those packages).
The problem occurs when I start the ROS bridge, I got the error ah shown in the video.
I also managed to install the bridge using option A (apt repository) and everything works well.
That's also the [video](https://drive.google.com/file/d/1Ww4L7BAj69Ma0OYniftm1AFvyhfAV5K_/view)

![Screenshot 2020-04-15 00:27:07](https://user-images.githubusercontent.com/11698175/79281280-b722a180-7eb2-11ea-8e40-ceacb9f40335.png)

**Comment by vimalrajliya** [comment]
Did you do `git submodule update --init` before doing `catkin_make`?
This problem might occur when you don't have the carla_msgs package.

**Comment by arstek131** [comment]
> Did you do `git submodule update --init` before doing `catkin_make`?
> This problem might occur when you don't have the carla_msgs package.

Thanks problem solved, that was the issue.
