### ISSUE TITLE
ROS2: port carla_ros_bridge

### ISSUE THREAD

**Issue by fpasch** [carla-simulator/ros-bridge#277]

**Comment by togaen** [comment]
Any status updates on this effort?

**Comment by ruffsl** [comment]
While porting the bridge to ROS2, would it be feasible to use something other than python for bridging between carla's server and ROS2/DDS? For conducting simulations of robotics systems with high bandwidth, low latency requirements, using the rclcpp client library would seem more appropriate for performance gains and potential for shared memory/zero-copy IPC transport.

https://carla.readthedocs.io/en/latest/core_world/#client-creation 

Does Carla have a C++ API for it's server side TCP client access? Is it possible to use something like pluginlib to write a ROS2 bridge plugin that could run in the same process hosting the Carla server, skipping the intermediary TCP serialization altogether?
