### ISSUE TITLE
ImportError: cannot import name Vehicle

### ISSUE THREAD

**Issue by vadbut** [carla-simulator/ros-bridge#28]
Hey,

I have the following error while launching the bridge node:
```
  File "/home/vadbut/catkin_ws/src/ros-bridge/src/carla_ros_bridge/ego_vehicle.py", line 25, in <module>
    from carla_ros_bridge import Vehicle
ImportError: cannot import name Vehicle
```
Simple stuff like sourcing setup.bash and rebuilding the module doesn't help. I use python 2.7. I tried rearranging the imports and it seems like everything else is being imported perfectly fine except for the Vehicle.

Thanks

**Comment by abhijeet1994** [comment]
did you find a solution? I am facing a similar issue
