### ISSUE TITLE
How to visualize via rviz by activating all sensors

### ISSUE THREAD

**Issue by Usaywook** [carla-simulator/ros-bridge#29]
When visualizing the values of the sensors via rvizf, only one sensor is visualized for one scene. Is there a way to visualize all sensor values? For example, if you turn on the lidar sensor, only the point cloud value is visualized and the other camera screen is stopped. Which part of a file does it need to be modified?

**Comment by fabianoboril** [comment]
Hi,
the ROS bridge provides the data for all *currently* active sensors. If you want to use a LiDAR and a camera in parallel, you need to add both sensors to your vehicle in your python client. In the manual_control.py only one sensor is active at a time.

**Comment by Usaywook** [comment]
How do I get two sensors on my client's car?

**Comment by fabianoboril** [comment]
Please see the CARLA documentation:
https://github.com/carla-simulator/carla/blob/master/Docs/python_api_tutorial.md#sensors

**Comment by Usaywook** [comment]
I have seen the CARLA documentation but have not gotten the answer.
I expect to have to modify the set_sensor method of the CameraManager object in the mannual_control.py file.
  If I want to install rgb, depth, semantic_segmentation, and Lidar sensors in your vehicle, how do I modify the set_sensor method function?
I made the following modification and I get an error.

![screenshot from 2019-01-11 21-06-38](https://user-images.githubusercontent.com/42348669/51032862-e0d08700-15e4-11e9-9810-112e4b098282.png)

**Comment by fabianoboril** [comment]
Hi,
I created a new branch (feature/example) that includes an example for a single vehicle with multiple sensors. If you use it with the rviz launch file, you will see multiple cameras and a lidar (point cloud). I still need to do some polishing, but you can try it out already.

**Comment by danil-tolkachev** [comment]
Hi @fabianoboril 
I tried your script (it works as intended). But I also found that the frame rate for the RGB image drops when the bridge is connected. For other topics, the frequency is stable.
![image](https://user-images.githubusercontent.com/12847693/51166824-d567af00-18b5-11e9-9603-02c8c41c28ae.png)

I assume that this effect is due to the competition of two subscribers to sensor data (pygame and ros-bridge). It may be worthwhile to publish not all the data in the ROS, but to filter some (for example, using role_name)?

**Comment by yyuuliang** [comment]
@danil-tolkachev hi, I am also using ROS bridge, however, i haven't seen these topics in my ROS message list, are you using the original ROS bridge code or did you modify the code by yourself? thanks.

**Comment by danil-tolkachev** [comment]
I used example from feature/example branch: https://github.com/carla-simulator/ros-bridge/blob/feature/example/single_vehicle_example.py

**Comment by fpasch** [comment]
`carla_ego_vehicle` now provides an easy way to setup an example ego vehicle.
