### ISSUE TITLE
ego_vehicle_control_info rosmsg

### ISSUE THREAD

**Issue by Usaywook** [carla-simulator/ros-bridge#30]
![ego_vehicle_control_info rosmsg](https://user-images.githubusercontent.com/42348669/51013929-a3e69f00-15a8-11e9-97de-21083f1a9869.png)
The topic message value of / carla / ego_vehicle / ego_vehicle_control_info is not output properly. When I tried rostopic echo / carla / ego_vehicle / ego_vehicle_control_info, the brake value at the output is being transmitted properly, but the throttle and brake are still fixed at 0.0. How can I fix this to get it to the right value? Which part of the file should I fix?

**Comment by fabianoboril** [comment]
Hi,
this msg is only an information msg. It only displays the states of the PID controller, that is used to translate an Ackermann control input into a throttle/brake command required by CARLA. The target in this msg is the Ackermann input (so to say the controller input), and the output is the command which is sent to CARLA.

In your case, the target (Ackermann command) contains a speed and acceleration of 0. Hence, the vehicle is supposed to not move, i.e. brake. And this is what the controller provides as state ('Braking'), and what is sent to CARLA (brake = 0.83....). If you would send an Ackermann msg to the ROS bridge with a positive speed/acceleration, then you would also see this change reflected in the output.

My guess is, that you drive around with the manual_control.py client, while the ROS bridge is running. In this case, there is no control input (neither throttle/brake, nor Ackermann) to the ROS bridge. Hence, the PID controller only shows the current state (current), and its default response to stop the car (however, this stop is not send to CARLA to avoid issues as described in #20.
