### ISSUE TITLE
Lidar data not visible in rviz

### ISSUE THREAD

**Issue by vedthakur5** [carla-simulator/ros-bridge#303]
I am using 
Carla: 0.9.9
Carla-ros -bridge: latest version and
Ubuntu:18.04
Ros: meloldic

this my launch file code:

<launch>
  
  <arg name='host' default='localhost'/>
  <arg name='port' default='2000'/>
  <arg name='timeout' default='2'/>

  
  <arg name='role_name' default='ego_vehicle'/>
  <arg name="vehicle_filter" default='vehicle.*'/>
  <arg name="spawn_point" default=""/>
  <arg name="sensor_definition_file" default="$(find carla_ego_vehicle)/config/sensors2.json"/>

  
  <arg name="town" default=''/>

  
  <arg name='synchronous_mode' default='True'/> 
  <arg name='synchronous_mode_wait_for_vehicle_control_command' default='False'/>
  <arg name='fixed_delta_seconds' default='0.05'/>

  <include file="$(find carla_ros_bridge)/launch/carla_ros_bridge.launch">
    <arg name='host' value='$(arg host)'/>
    <arg name='port' value='$(arg port)'/>
    <arg name='town' value='$(arg town)'/>
    <arg name='timeout' value='$(arg timeout)'/>
    <arg name='synchronous_mode' value='$(arg synchronous_mode)'/>
    <arg name='synchronous_mode_wait_for_vehicle_control_command' value='$(arg synchronous_mode_wait_for_vehicle_control_command)'/>
    <arg name='fixed_delta_seconds' value='$(arg fixed_delta_seconds)'/>
  </include>

  <include file="$(find carla_ego_vehicle)/launch/carla_example_ego_vehicle.launch">
    <arg name='host' value='$(arg host)'/>
    <arg name='port' value='$(arg port)'/>
    <arg name='timeout' value='$(arg timeout)'/>
    <arg name="vehicle_filter" value='$(arg vehicle_filter)'/>
    <arg name='role_name' value='$(arg role_name)'/>
    <arg name="spawn_point" value="$(arg spawn_point)"/>
    <arg name="sensor_definition_file" value='$(arg sensor_definition_file)'/>
  </include>

  <include file="$(find carla_manual_control)/launch/carla_manual_control.launch">
    <arg name='role_name' value='$(arg role_name)'/>
  </include>

  
  <node pkg="rviz" type="rviz" name="rviz" args="-d $(find carla_ros_bridge)/config/bro.rviz" required="true" output="screen"/>
  

</launch>

This is my sensors2.json file:

{
    "sensors": [
        {
            "type": "sensor.camera.rgb",
            "id": "front",
            "x": 2.0, "y": 0.0, "z": 2.0, "roll": 0.0, "pitch": 0.0, "yaw": 0.0,
            "width": 800,
            "height": 600,
            "fov": 100,
            "sensor_tick": 0.05,
            "gamma": 2.2,
            "shutter_speed": 60.0,
            "iso": 1200.0,
            "fstop": 1.4,
            "min_fstop": 1.2,
            "blade_count": 5,
            "exposure_mode": "manual",
            "exposure_compensation": 3.0,
            "exposure_min_bright": 0.1,
            "exposure_max_bright": 2.0,
            "exposure_speed_up": 3.0,
            "exposure_speed_down": 1.0,
            "calibration_constant": 16.0,
            "focal_distance": 1000.0,
            "blur_amount": 1.0,
            "blur_radius": 0.0,
            "motion_blur_intensity": 0.45,
            "motion_blur_max_distortion": 0.35,
            "motion_blur_min_object_screen_size": 0.1,
            "slope": 0.88,
            "toe": 0.55,
            "shoulder": 0.26,
            "black_clip": 0.0,
            "white_clip": 0.04,
            "temp": 6500.0,
            "tint": 0.0,
            "chromatic_aberration_intensity": 0.0,
            "chromatic_aberration_offset": 0.0,
            "enable_postprocess_effects": "True",
            "lens_circle_falloff": 5.0,
            "lens_circle_multiplier": 0.0,
            "lens_k": -1.0,
            "lens_kcube": 0.0,
            "lens_x_size": 0.08,
            "lens_y_size": 0.08
        },
        {
            "type": "sensor.camera.rgb",
            "id": "view",
            "x": -4.5, "y": 0.0, "z": 2.8, "roll": 0.0, "pitch": -20.0, "yaw": 0.0,
            "width": 800,
            "height": 600,
            "fov": 100,
            "sensor_tick": 0.05,
            "gamma": 2.2,
            "shutter_speed": 60.0,
            "iso": 1200.0,
            "fstop": 1.4,
            "min_fstop": 1.2,
            "blade_count": 5,
            "exposure_mode": "manual",
            "exposure_compensation": 3.0,
            "exposure_min_bright": 0.1,
            "exposure_max_bright": 2.0,
            "exposure_speed_up": 3.0,
            "exposure_speed_down": 1.0,
            "calibration_constant": 16.0,
            "focal_distance": 1000.0,
            "blur_amount": 1.0,
            "blur_radius": 0.0,
            "motion_blur_intensity": 0.45,
            "motion_blur_max_distortion": 0.35,
            "motion_blur_min_object_screen_size": 0.1,
            "slope": 0.88,
            "toe": 0.55,
            "shoulder": 0.26,
            "black_clip": 0.0,
            "white_clip": 0.04,
            "temp": 6500.0,
            "tint": 0.0,
            "chromatic_aberration_intensity": 0.0,
            "chromatic_aberration_offset": 0.0,
            "enable_postprocess_effects": "True",
            "lens_circle_falloff": 5.0,
            "lens_circle_multiplier": 0.0,
            "lens_k": -1.0,
            "lens_kcube": 0.0,
            "lens_x_size": 0.08,
            "lens_y_size": 0.08
        },
        {
            "type": "sensor.lidar.ray_cast",
            "id": "lidar1",
            "x": 0.0, "y": 0.0, "z": 2.4, "roll": 0.0, "pitch": 0.0, "yaw": 0.0,
            "range": 50,
            "channels": 32,
            "points_per_second": 320000,
            "upper_fov": 2.0,
            "lower_fov": -26.8,
            "rotation_frequency": 20,
            "sensor_tick": 0.0
        },
        {
            "type": "sensor.other.radar",
            "id": "front",
            "x": 2.0, "y": 0.0, "z": 1.5, "roll": 0.0, "pitch": 0.0, "yaw": 0.0,
            "horizontal_fov": 30.0,
            "vertical_fov": 10.0,
            "points_per_second": 1500,
            "range": 100.0
        },
        {
            "type": "sensor.other.gnss",
            "id": "gnss1",
            "x": 1.0, "y": 0.0, "z": 2.0,
            "noise_alt_stddev": 0.0, "noise_lat_stddev": 0.0, "noise_lon_stddev": 0.0,
            "noise_alt_bias": 0.0, "noise_lat_bias": 0.0, "noise_lon_bias": 0.0
        },
        {
            "type": "sensor.other.imu",
            "id": "imu1",
            "x": 2.0, "y": 0.0, "z": 2.0, "roll": 0.0, "pitch": 0.0, "yaw": 0.0,
            "noise_accel_stddev_x": 0.0, "noise_accel_stddev_y": 0.0, "noise_accel_stddev_z": 0.0,
            "noise_gyro_stddev_x": 0.0, "noise_gyro_stddev_y": 0.0, "noise_gyro_stddev_z": 0.0,
            "noise_gyro_bias_x": 0.0, "noise_gyro_bias_y": 0.0, "noise_gyro_bias_z": 0.0
        },
        {
            "type": "sensor.other.collision",
            "id": "collision1",
            "x": 0.0, "y": 0.0, "z": 0.0
        },
        {
            "type": "sensor.other.lane_invasion",
            "id": "laneinvasion1",
            "x": 0.0, "y": 0.0, "z": 0.0
        }
    ]
}

This is my bro.rviz file
Panels:
  - Class: rviz/Displays
    Help Height: 78
    Name: Displays
    Property Tree Widget:
      Expanded:
        - /Global Options1
        - /Status1
      Splitter Ratio: 0.5
    Tree Height: 233
  - Class: rviz/Selection
    Name: Selection
  - Class: rviz/Tool Properties
    Expanded:
      - /2D Pose Estimate1
      - /2D Nav Goal1
      - /Publish Point1
    Name: Tool Properties
    Splitter Ratio: 0.5886790156364441
  - Class: rviz/Views
    Expanded:
      - /Current View1
    Name: Views
    Splitter Ratio: 0.5
  - Class: rviz/Time
    Experimental: false
    Name: Time
    SyncMode: 0
    SyncSource: Camera
  - Class: rviz_carla_plugin/CarlaControl
    Name: CarlaControl
Preferences:
  PromptSaveOnExit: true
Toolbars:
  toolButtonStyle: 2
Visualization Manager:
  Class: ""
  Displays:
    - Alpha: 0.5
      Cell Size: 1
      Class: rviz/Grid
      Color: 160; 160; 164
      Enabled: true
      Line Style:
        Line Width: 0.029999999329447746
        Value: Lines
      Name: Grid
      Normal Cell Count: 0
      Offset:
        X: 0
        Y: 0
        Z: 0
      Plane: XY
      Plane Cell Count: 10
      Reference Frame: <Fixed Frame>
      Value: true
    - Class: rviz/Image
      Enabled: true
      Image Topic: /carla/ego_vehicle/camera/rgb/view/image_color
      Max Value: 1
      Median window: 5
      Min Value: 0
      Name: Image
      Normalize Range: true
      Queue Size: 2
      Transport Hint: raw
      Unreliable: false
      Value: true
    - Class: rviz/Image
      Enabled: true
      Image Topic: /carla/ego_vehicle/camera/rgb/front/image_color
      Max Value: 1
      Median window: 5
      Min Value: 0
      Name: Image
      Normalize Range: true
      Queue Size: 2
      Transport Hint: raw
      Unreliable: false
      Value: true
    - Alpha: 1
      Autocompute Intensity Bounds: true
      Autocompute Value Bounds:
        Max Value: 10
        Min Value: -10
        Value: true
      Axis: Z
      Channel Name: intensity
      Class: rviz/PointCloud
      Color: 255; 255; 255
      Color Transformer: Intensity
      Decay Time: 0
      Enabled: true
      Invert Rainbow: false
      Max Color: 255; 255; 255
      Max Intensity: 4096
      Min Color: 0; 0; 0
      Min Intensity: 0
      Name: PointCloud
      Position Transformer: XYZ
      Queue Size: 10
      Selectable: true
      Size (Pixels): 3
      Size (m): 0.009999999776482582
      Style: Flat Squares
      Topic: /carla/ego_vehicle/lidar/front/point_cloud
      Unreliable: false
      Use Fixed Frame: true
      Use rainbow: true
      Value: true
    - Class: rviz/Marker
      Enabled: true
      Marker Topic: /carla/marker
      Name: Marker
      Namespaces:
        {}
      Queue Size: 100
      Value: true
  Enabled: true
  Global Options:
    Background Color: 48; 48; 48
    Default Light: true
    Fixed Frame: map
    Frame Rate: 30
  Name: root
  Tools:
    - Class: rviz/Interact
      Hide Inactive Objects: true
    - Class: rviz/MoveCamera
    - Class: rviz/Select
    - Class: rviz/FocusCamera
    - Class: rviz/Measure
    - Class: rviz/SetInitialPose
      Theta std deviation: 0.2617993950843811
      Topic: /initialpose
      X std deviation: 0.5
      Y std deviation: 0.5
    - Class: rviz/SetGoal
      Topic: /move_base_simple/goal
    - Class: rviz/PublishPoint
      Single click: true
      Topic: /clicked_point
  Value: true
  Views:
    Current:
      Class: rviz/Orbit
      Distance: 10
      Enable Stereo Rendering:
        Stereo Eye Separation: 0.05999999865889549
        Stereo Focal Distance: 1
        Swap Stereo Eyes: false
        Value: false
      Focal Point:
        X: 0
        Y: 0
        Z: 0
      Focal Shape Fixed Size: true
      Focal Shape Size: 0.05000000074505806
      Invert Z Axis: false
      Name: Current View
      Near Clip Distance: 0.009999999776482582
      Pitch: 0.6703979969024658
      Target Frame: <Fixed Frame>
      Value: Orbit (rviz)
      Yaw: 0.895399808883667
    Saved: ~
Window Geometry:
  Displays:
    collapsed: false
  Height: 846
  Hide Left Dock: false
  Hide Right Dock: false
  Image:
    collapsed: false
  QMainWindow State: 000000ff00000000fd000000040000000000000156000002b0fc0200000009fb0000001200530065006c0065006300740069006f006e00000001e10000009b0000005c00fffffffb000000120056006900650077007300200054006f006f02000001df000002110000018500000122fb000000200054006f006f006c002000500072006f0070006500720074006900650073003203000002880000011d000002210000017afb0000001e0054006f006f006c002000500072006f0070006500720074006900650073010000003d000000a30000005c00fffffffb000000100044006900730070006c00610079007301000000e600000174000000c900fffffffb0000002000730065006c0065006300740069006f006e00200062007500660066006500720200000138000000aa0000023a00000294fb00000014005700690064006500530074006500720065006f02000000e6000000d2000003ee0000030bfb0000000c004b0069006e0065006300740200000186000001060000030c00000261fb0000000a0049006d00610067006501000002600000008d0000001600ffffff000000010000010f000002b0fc0200000003fb0000001e0054006f006f006c002000500072006f00700065007200740069006500730100000041000000780000000000000000fb0000000a00560069006500770073010000003d000002b0000000a400fffffffb0000001200530065006c0065006300740069006f006e010000025a000000b200000000000000000000000200000490000000a9fc0100000001fb0000000a00560069006500770073030000004e00000080000002e10000019700000003000004b00000003efc0100000002fb0000000800540069006d00650100000000000004b0000002eb00fffffffb0000000800540069006d006501000000000000045000000000000000000000023f000002b000000004000000040000000800000008fc0000000100000002000000010000000a0054006f006f006c00730100000000ffffffff0000000000000000
  Selection:
    collapsed: false
  Time:
    collapsed: false
  Tool Properties:
    collapsed: false
  Views:
    collapsed: false
  Width: 1200
  X: 67
  Y: 27

I am getting the camera sensors but i am not able to see lidar sensor output on rviz

**Comment by vedthakur5** [comment]
I forgot to post the launch file
Launch file :


<launch>
  
  <arg name='host' default='localhost'/>
  <arg name='port' default='2000'/>
  <arg name='timeout' default='2'/>

  
  <arg name='role_name' default='ego_vehicle'/>
  <arg name="vehicle_filter" default='vehicle.*'/>
  <arg name="spawn_point" default=""/>
  <arg name="sensor_definition_file" default="$(find carla_ego_vehicle)/config/sensors2.json"/>

  
  <arg name="town" default=''/>

  
  <arg name='synchronous_mode' default='True'/> 
  <arg name='synchronous_mode_wait_for_vehicle_control_command' default='False'/>
  <arg name='fixed_delta_seconds' default='0.05'/>


  <include file="$(find carla_ros_bridge)/launch/carla_ros_bridge.launch">
    <arg name='host' value='$(arg host)'/>
    <arg name='port' value='$(arg port)'/>
    <arg name='town' value='$(arg town)'/>
    <arg name='timeout' value='$(arg timeout)'/>
    <arg name='synchronous_mode' value='$(arg synchronous_mode)'/>
    <arg name='synchronous_mode_wait_for_vehicle_control_command' value='$(arg synchronous_mode_wait_for_vehicle_control_command)'/>
    <arg name='fixed_delta_seconds' value='$(arg fixed_delta_seconds)'/>
  </include>

  <include file="$(find carla_ego_vehicle)/launch/carla_example_ego_vehicle.launch">
    <arg name='host' value='$(arg host)'/>
    <arg name='port' value='$(arg port)'/>
    <arg name='timeout' value='$(arg timeout)'/>
    <arg name="vehicle_filter" value='$(arg vehicle_filter)'/>
    <arg name='role_name' value='$(arg role_name)'/>
    <arg name="spawn_point" value="$(arg spawn_point)"/>
    <arg name="sensor_definition_file" value='$(arg sensor_definition_file)'/>
  </include>

  <include file="$(find carla_manual_control)/launch/carla_manual_control.launch">
    <arg name='role_name' value='$(arg role_name)'/>
  </include>

  
  <node pkg="rviz" type="rviz" name="rviz" args="-d $(find carla_ros_bridge)/config/bro.rviz" required="true" output="screen"/>
  

</launch>

**Comment by vedthakur5** [comment]
I don't kow why the launch files is not being printed here so i have posted a pic:
![Screenshot from 2020-06-03 11-29-44](https://user-images.githubusercontent.com/64027060/83601257-d920d200-a58d-11ea-9776-30b8112e421a.png)

**Comment by fpasch** [comment]
Please compare with launch configuration carla_ad_demo_with_rviz.launch from carla_ad_demo

**Comment by vedthakur5** [comment]
Ya thanks for your comment....actually my pointcloud topic was wrong...originally it is 
Topic: /carla/ego_vehicle/lidar/front/point_cloud
but it should be
Topic: /carla/ego_vehicle/lidar/lidar1/point_cloud
as the id of lidar sensor is lidar1 in sensors.json
