### ISSUE TITLE
Carla AD Demo Scenario: FollowLeadingVehicle Target is not moving

### ISSUE THREAD

**Issue by Roosstef** [carla-simulator/ros-bridge#305]
Hey all,

when Im starting the FollowLeadingVehicle.osx Scenario in the carla_ad_demo.launch the target vehicle is not moving. When spawning normal npcs with spawn_npc.py they are moving. 
Is this a bug in the ros-bridge or a bug in the used FollowLeadingVehicle.xosc file?

This file also differs from the FollowLeadingVehicle.xosc I found in the scenario_runner repo.

Are there any guides to convert the xosc files to use them with  carla_ad_demo.launch?

**Comment by fpasch** [comment]
It should move. But due to synchronous mode it might take some time.

**Comment by dvh549** [comment]
Hi @fpasch, I tried executing the scenario and waited for the ego vehicle to move but it didn't. I tried multiple times but the scenario always fails at execution and status turns to red. However, the spawned npcs moved as per norm after awhile. Upon closer look, I found these errors in the terminal as shown in the images. Please advise on how to proceed.
![Screenshot from 2020-06-16 16-40-53](https://user-images.githubusercontent.com/59161350/84753229-4c483080-aff1-11ea-84c1-fa4d423d9aad.png)
![unable to parse xml string](https://user-images.githubusercontent.com/59161350/84753324-6f72e000-aff1-11ea-9d87-bc060d48eaf1.png)
