### ISSUE TITLE
Ros-Bridge in WSL, in Windows 10

### ISSUE THREAD

**Issue by MichaelKlin** [carla-simulator/ros-bridge#306]
Hi, i install last version of Carla on Windows 10 and want to use ROS-Bridge. I install Ros Melodic on my WSL in Windows and it looks like working. Can i install ros bridge in wsl and use carla on windows? Or should i share my egg-file? Can you please help?

**Comment by EsmanurCvl** [comment]
hi i have same problem . i can't find any source about carla -ros bridge on windows 10 . Did you find  any solutions about that ?
