### ISSUE TITLE
Documentation Request: Synchronous mode and NPCs

### ISSUE THREAD

**Issue by faultfactory** [carla-simulator/ros-bridge#312]
Hello, 

Carla 0.9.9.2 on 18.04

There's little documentation related to spawning npc's with the ros bridge setup. 
Currently i'm starting a (separate) carla server on my network, ssh'ing into it and running spawn_npcs.py with the --sync option.  When I do that, I see the image output changes in a manner that shows the two computation steps. 
One frame is shown that shows the npc movement and the next frame shows the ego vehicle movement. Simultaneously the radar outputs all have velocity = 0.

When I kill the spawn_npc.py task, the radar information does not return to having the expected velocity so something breaks and i need to restart. 

The ros documentation shows that other clients need to passively wait. It's not clear how to do that exactly. I tried without the --sync option and i get the same result. 

Is it possible to integrate some of the spawn_npc functionality into the ros bridge node? I attempted this but got an rpc error but i don't work with the api much. Perhaps it requires creating another node that handles the traffic manager. 

Any information would be very helpful.

**Comment by fpasch** [comment]
The issues you ran into seem to be related to the problem, that currently, in synchronous mode, all clients would need to sync themselves. For the ROS use case, the carla-ros-bridge expects to be the only ticking client currently. 

In general, it would totally make sense to have support for spawning other traffic participants from ROS-side. I would vote for having that feature within a separate ros-node, e.g. with some service calls. If you're interested in implementing such node, please contact me in discord.

Please also have a look at carla scenario runner (and its ROS integration) that allows to spawn vehicles and let them follow routes.
