### ISSUE TITLE
how can I see multiple images in rviz?

### ISSUE THREAD

**Issue by minwo0jung** [carla-simulator/ros-bridge#320]
![Screenshot from 2020-06-17 00-09-32](https://user-images.githubusercontent.com/57853087/84792494-debaf500-b02e-11ea-8864-a69f80f2d15e.png)
I want to see in rviz using carla's mannnual_control.py and ros bridge, but only the cameras running in pygame excuted in mannual_control.py are displayed in rviz. Even if it doesn't work in pygame, II want to appear in images 1,2,3 at a time within rviz and ask how to make observations.

I tried synchronous mode = true in settings.yaml to run synchronous mode, but nothing changed

**Comment by fpasch** [comment]
Using carla's manual_control.py is not recommended. Please use carla_manual_control from this repo. As this is only the visualization part, you also need carla_ego_vehicle to spawn the ego vehicle. In sensors.json you can then define multiple cameras. All camera image streams can also be visualized in rviz).

You might be able to use carla's manual control, but you might run into issues, especially when using the synchronous mode.
