### ISSUE TITLE
Carla Server Crashes upon load of AD Demo

### ISSUE THREAD

**Issue by dvh549** [carla-simulator/ros-bridge#321]
Hi all,

Upon trying to run the AD Demo, the Carla Server crashes and a low level fatal error is thrown. Kindly advise on how to proceed.

Carla Version: 0.9.9.3
OS: Ubuntu 18.04

![image](https://user-images.githubusercontent.com/59161350/84883886-afa29300-b0c3-11ea-927b-e70bc2c50d7c.png)

**Comment by fpasch** [comment]
Are you still able to reproduce the issue?

**Comment by dvh549** [comment]
Hi @fpasch , I do not face this error anymore. Thanks.
