### ISSUE TITLE
Wrong frame_id of carla/ego_vehicle/vehicle_status topic

### ISSUE THREAD

**Issue by haisongdong-harrison** [carla-simulator/ros-bridge#325]
I was trying to find a topic to extract the status of the ego vehicle. Both `/carla/ego_vehicle/vehicle_status` and `/carla/objects` seem to be potential candidates for the purpose, despite I need some filtering for the latter.

Somehow I noticed some discrepancies between the two topics that really look like a bug to me.
I recorded a ROS bag and compared the two topics at the same timestamp side-by-side. Here's a screenshot of it.
![image](https://user-images.githubusercontent.com/13168445/85677396-78a33180-b702-11ea-8ec1-696a9e9f5de2.png)
`/carla/ego_vehicle/vehicle_status` on the left and `/carla/objects` on the right, expanded to the object that corresponds to the `ego_vehicle` (you can see the orientation fields are matching perfectly).

According to the `frame_id`, both topics should be representing the status of the `ego_vehicle` in the same "map" frame. However, acceleration values don't really agree with each other. The magnitudes are very close on the three axes but the signs differ. `/carla/objects` does seem to have things in the `map` frame but `/carla/ego_vehicle/vehicle_status` is more like ... in `ego_vehicle` I guess? Is the `frame_id` of `/carla/ego_vehicle/vehicle_status` wrong?

**Comment by D-2n** [comment]
Can you please say what program you are using to plot the bags? I really need to extract acceleration data and plot it!
