### ISSUE TITLE
new Carla Update Lidar with Intensity 

### ISSUE THREAD

**Issue by Roosstef** [carla-simulator/ros-bridge#329]
Hi all,

since the new carla Update with introduces Intensity to the Lidar sensor, the ros bridge crashes by reshape error because of missing 4th channel in ros bridge lidar.py.

**Comment by marcgpuig** [comment]
@Roosstef thanks for pointing it out!
@joel-mb is currently fixing it.

**Comment by joel-mb** [comment]
Hi @Roosstef, we've merged a PR fixing the issue. Thanks!
