### ISSUE TITLE
[Question] Map visualization on RVIZ

### ISSUE THREAD

**Issue by bbrito** [carla-simulator/ros-bridge#332]
Dear ros-bridge team,

Is it possible to visualize the map of the city in RVIZ?

Best regards,
Bruno

**Comment by joel-mb** [comment]
Hi @bbrito!
Unfortunately, we don't have any package to visualize the CARLA towns out of the box yet. So far, I can think of two possibilities:

* Using the point cloud maps provided in this repo (https://bitbucket.org/carla-simulator/autoware-contents.git). We are using this approach in the integration with autoware.
* Try to export the mesh from Unreal and then use a ros Marker to visualize it.

Hope this helps!

**Comment by bbrito** [comment]
Hi @joel-mb!

Thanks for the advice. I will try the first option.

Best regards,
Bruno

**Comment by konradst** [comment]
Why have you closed it?
