### ISSUE TITLE
Visualize CarlaRadarMeasurements

### ISSUE THREAD

**Issue by Roosstef** [carla-simulator/ros-bridge#336]
Hi all,

is there currently a way to visualize the CarlaRadarMeasurements in Rviz with e.g. Pointcloud2 or ainstein_radar_msgs?

Greetings
Stefan

**Comment by fpasch** [comment]
There is currently no rviz plugin for visualizing. You might be able to create a converter node from CarlaRadarMeasurements to ainstein_radar_msgs and use their visualization.
