### ISSUE TITLE
How visualize the carla opendrive map on rviz

### ISSUE THREAD

**Issue by XieJinLiang** [carla-simulator/ros-bridge#347]
Hi,
Is there a way to visualize the carla opendrive map on rviz?What message type should I use?Or can I only draw it line by line manually?

**Comment by fpasch** [comment]
There is no visualization available yet.
For visualization purposes you would use [MarkerArray](http://docs.ros.org/melodic/api/visualization_msgs/html/msg/MarkerArray.html) messages.

You could use [carla-map](https://github.com/carla-simulator/map) for loading the opendrive map and then [query](https://ad-map-access.readthedocs.io/en/latest/ad_map_access/apidoc/html/namespacead_1_1map_1_1lane.html#ac77c4814fcedd0ec729db78e3169baf6) it. Please find additional documentation [here](https://ad-map-access.readthedocs.io/en/latest/).

Feel free to create a pull request.
