### ISSUE TITLE
ROS bridge doesn't work in Synchronous mode

### ISSUE THREAD

**Issue by telecaster00** [carla-simulator/ros-bridge#394]
I posted to below, but I should have posted here.
If anyone knows, please help.

https://github.com/carla-simulator/carla/issues/3456

I am currently using manual_control.py below.
https://github.com/carla-simulator/carla/blob/dev/PythonAPI/examples/manual_control.py

Should I use carla_manual_control.py below?
https://github.com/carla-simulator/ros-bridge/blob/master/carla_manual_control/src/carla_manual_control/carla_manual_control.py

**Comment by fpasch** [comment]
Yes. When using the ros bridge, please use carla_manual_control. ROS bridge handles the "ticking".
