### ISSUE TITLE
Lidar Data - Conversion to Numpy array fails - TypeError: fromstring() argument 1 must be read-only bytes-like object, not memoryview

### ISSUE THREAD

**Issue by jiyojolly** [carla-simulator/ros-bridge#400]
Error when running carla_ros_bridge with python 3. 
Error:  
`/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 68, in sensor_data_updated
    lidar_data = numpy.fromstring(
TypeError: fromstring() argument 1 must be read-only bytes-like object, not memoryview
`
I was able to fix the issue by casting to bytes.
`lidar_data = numpy.fromstring(
            bytes(carla_lidar_measurement.raw_data), dtype=numpy.float32)`
I don't know if this is the correct way. 

Ubuntu 20.04
ROS Noetic
Carla Version: 0.9.10
ROS Bridge: Latest Master - d991747cb4c473704f1a623c7757978753e7ff13

**Comment by joel-mb** [comment]
Hi @jiyojolly ! Thanks for reporting the issue. We've just opened a PR to fix it.
