### ISSUE TITLE
Crashes while replaying certain CARLA state logs

### ISSUE THREAD

**Issue by FHof** [carla-simulator/ros-bridge#449]
I've described this problem and reproduction steps there in detail: https://github.com/carla-simulator/carla/issues/3544
Since the crash happens when I use the Rosbridge, I'm not sure at which repository the issue belongs, so I'm opening an Issue here, too.

A workaround against this problem is to remove the code where the crash happens:
```
sed -n '/shape.dimension/,/x.extent.z/ !p' -i "/home/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/traffic_participant.py"
sed -n '/pose = trans/,/x.extent.z/ !p' -i "/home/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/actor.py"
```
I haven't tested this workaround with the newest Rosbridge changes.
With the newest Rosbridge a workaround is to remove the markers and objects Pseudo sensors.

**Comment by hofbi** [comment]
@fpasch Do you have any idea why this could happen. I actually don't see any changes in the ros bridge and the python API that would cause this:

| 0.9.8 | 0.9.10 |
| ------ | ------ |
| [Docs](https://carla.readthedocs.io/en/0.9.8/python_api/#carlavehicle) | [Docs](https://carla.readthedocs.io/en/0.9.10/python_api/#carlavehicle) |
| [Bridge](https://github.com/carla-simulator/ros-bridge/blob/0.9.8/carla_ros_bridge/src/carla_ros_bridge/traffic_participant.py#L74) | [Bridge](https://github.com/carla-simulator/ros-bridge/blob/0.9.10.1/carla_ros_bridge/src/carla_ros_bridge/traffic_participant.py#L81) |
