### ISSUE TITLE
sensor.other.lane_detector Actor not detected by ros-bridge

### ISSUE THREAD

**Issue by mallela** [carla-simulator/ros-bridge#47]
Hello,

I am using Carla 0.9.3 on Ubuntu 16.04

I can get the ros-bridge to publish the sensor.other.collision data but I am unable to do the same for the sensor.other.lane_detector. Is there some implementation difference between the two sensors? How do I detect the sensor.other.lane_detector actor?

Thanks,
Praneeta

**Comment by fpasch** [comment]
This was a "bug" in Carla. It's fixed with Carla 0.9.5
