### ISSUE TITLE
Carla ros bridge doesn't find python

### ISSUE THREAD

**Issue by Johanfanas** [carla-simulator/ros-bridge#479]
Hi,

I downloaded the carla simulator and created a ROS workspace for the ros-bridge. I have everything setup properly but I am getting this error when launching the ros bridge "/usr/bin/env: ‘python’: No such file or directory". I am using Ubuntu 20.04. In this OS, python is not located in /usr/bin/env, so how do I tell the ros bridge where to find python ?

![Screenshot from 2021-02-09 16-24-25](https://user-images.githubusercontent.com/62773660/107430574-532d3180-6af3-11eb-880d-1617c5f31c01.png)

**Comment by fpasch** [comment]
Please try:
```
sudo apt install python-is-python3
```

**Comment by Johanfanas** [comment]
Thanks a lot, that helps. Now I am getting an error saying the ros bridge I have requieres Carla 0.9.10, but I saw the Carla repo and it says the Carla version 0.9.10 is only compatible for Ubuntu 18.04. Any suggestions ?

**Comment by hofbi** [comment]
0.9.10 also works on 20.04, but you need to download the release directly from github: https://github.com/carla-simulator/carla/releases/tag/0.9.10.1

The issue https://github.com/carla-simulator/carla/issues/3441 tracks the progress for supporting the releases on the carla ppa.

**Comment by joel-mb** [comment]
Closing the issue as the latest CARLA version has been added to the apt repo for focal.
Please, feel free to reopen the issue if the problem persists.
