### ISSUE TITLE
Passing cartographic and more information.

### ISSUE THREAD

**Issue by silgon** [carla-simulator/ros-bridge#48]
I would like to know if there is somewhere available the information about traffict lights, current lane of the vehicle and even weather as a ros message. I ask because this kind of data may be useful for training models.
I run the standard `client.launch` but it seems the information I'm talking about is not there.

Thanks in advance.

**Comment by fpasch** [comment]
This is now possible through carla_waypoint_publisher services and carla_ros_bridge topics.
