### ISSUE TITLE
carla_spawn_objects missing in apt package

### ISSUE THREAD

**Issue by blackliner** [carla-simulator/ros-bridge#489]
see topic

**Comment by hofbi** [comment]
Currently the latest release available in the apt package is [`0.9.10.1`](https://github.com/carla-simulator/ros-bridge/tree/0.9.10.1) which was before the `carla_ego_evhicle` and `carla_infrastructure` got merged into `carla_spawn_objects`. So in case you want to use this, you need to build the ros bridge from source or wait unit 0.9.11 is released.
