### ISSUE TITLE
'ascii' codec can't decode byte 0xc2

### ISSUE THREAD

**Issue by silgon** [carla-simulator/ros-bridge#49]
As I was doing data collection with ros-bridge, I encountered the following problem with the bagfiles.

    'ascii' codec can't decode byte 0xc2

This problem is know for messages (https://answers.ros.org/question/240612/rosbag-unicodedecodeerror/?answer=242610#post-id-242610). Quoting the answer:

> Just check which of your message definitions are UTF-8 encoded by the command line tool `file yourMessageDefinition.msg`. If it tells you `ASCII text` the definition should be OK, if `UTF-8 Unicode` text it is not.

While debugging I found out that the problem comes specifically from the message `/carla/ego_vehicle/ego_vehicle_control_info`.

Everything else seems correct. I'll check it out myself and if I find a solution I'll let you know.

**Comment by silgon** [comment]
Apparently as I described in the question, it was the encoding. Here is the following command to solved the issue.
```bash
cd ros-bridge/msg
for i in *.msg;  do
  iconv -f utf-8 -t ascii//TRANSLIT -o $i $i;
done
```
I think you should add it in a commit to your repository.

**Comment by mallela** [comment]
My guess is that the error is due to values like `2.34E-5` in the ROS published messages. 
My work around was changing the line in `/opt/ros/<ros-distro>/lib/python2.7/dist-packages/genpy/dynamic.py` from 
`tmp_file.file.write(full_text.encode())` to 
`tmp_file.file.write(full_text)`

**Comment by silgon** [comment]
Thanks for the commend @mallela , it's nice to see your workaround. However, that would mean that `genpy/dynamic.py` is incorrect because it can cause this kind of problems. Not sure if it's really either the `*.msg` files that are incorrect (that's what I want to believe) or carla's ros-bridge implementation.

One more thing, I'm using the docker images from **osrf**, and that would mean to change that based image, or at least the genpy package.

Are you using docker or you're doing it without containers?

**Comment by mallela** [comment]
Hi @silgon, No, I'm not using a docker/container.

**Comment by fpasch** [comment]
@silgon Are you still facing the issue?
I executed your shell-script, but it didn't change anything.

**Comment by silgon** [comment]
The script I added corrected my issue for the ros messages. But I haven't been using `ros-bridge` lately.

**Comment by fpasch** [comment]
Ok. Then let's assume that the msg-files are clean now. Thanks for your reply.
