### ISSUE TITLE
Rate of publishing is low - all messages updated in vehicle.py

### ISSUE THREAD

**Issue by mallela** [carla-simulator/ros-bridge#50]
Hello,

I am using ros-brige with CARLA 0.9.3 on Ubuntu 16.04

I noticed that all the messages updated by the Vehicle class have a low publish rate - even lower than depth and image publishing rates!

What is the reason this low rate?

Thanks,
Praneeta

**Comment by fpasch** [comment]
Is this still happening?

**Comment by mallela** [comment]
It has improved with the new ros-bridge by leaps and bounds probably due to decoupling the code for control and ego_vehicle class. But all the messages updated by the Vehicle class still have a slightly lower publishing rate that RGB/segmentation/depth (observed by using rostopic hz).

Tl;dr: Publishing rate looks reasonable. Thanks for the update!

**Comment by fpasch** [comment]
With #148 this should no longer be a problem.
