### ISSUE TITLE
Multiple sensor values for the same timestamp

### ISSUE THREAD

**Issue by mallela** [carla-simulator/ros-bridge#51]
Hello,

There are multiple sensor values in the bag file for the same header.stamp. I can't seem to solve this. Any ideas?

Ubuntu 16.04; Carla 0.9.3

Thanks,
Praneeta

**Comment by fpasch** [comment]
which sensor are you talking about?
Is it still happening?

**Comment by mallela** [comment]
I had the issue that the timestamp was exactly the same for 2 different RGB image messages. In addition in the /clock topic, the timestamps are repeating. 

Also, I wanted to ask if there was a reason/advantage that is not readily obvious to me that we use current carla time as opposed to system time to stamp the data being published? Are there any disadvantages to using system time?

**Comment by slinshady89** [comment]
Probably this helps you with your issue. 
https://carla.readthedocs.io/en/latest/configuring_the_simulation/#synchronous-mode

**Comment by fpasch** [comment]
With #148 carla ros bridge support synchronous mode.
