### ISSUE TITLE
Camera TF orientation problem

### ISSUE THREAD

**Issue by KevinLADLee** [carla-simulator/ros-bridge#511]
Hi! I tested the 0.9.11 version of carla with the ros-bridge master branch and found a problem. the camera visualization option in Rviz does not display the point cloud to RGB image projection properly. This problem is not present in the 0.9.10.1 version of ros-bridge. It seems to be caused by the wrong orientation of the camera coordinate system. Hopefully, this issue can be attended to.
![image](https://user-images.githubusercontent.com/15060244/112271359-cced3900-8cb5-11eb-901b-335f5efbe643.png)

**Comment by KevinLADLee** [comment]
FYI
![b1_xyz_pinhole_camera_coordiantes](https://user-images.githubusercontent.com/15060244/112272713-80a2f880-8cb7-11eb-9544-ccd0107c9f90.jpg)

**Comment by joel-mb** [comment]
Hi @KevinLADLee. Thanks for reporting the issue. I've introduced the fixes in the following branch: https://github.com/carla-simulator/ros-bridge/tree/joel-mb/fix_camera_tf. Could you confirm that this is fixing the issue?

**Comment by KevinLADLee** [comment]
![Screenshot from 2021-03-29 20-44-03](https://user-images.githubusercontent.com/15060244/112838362-90637800-90cf-11eb-853b-4c1498239962.png)
I think it works well. Thanks a lot!
