### ISSUE TITLE
Unable to use carla_spawn_objects to spawn vehicle with role_name other than 'ego_vehicle'

### ISSUE THREAD

**Issue by pricejiang** [carla-simulator/ros-bridge#517]
Hi, I am trying to spawn vehicle by using the `ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py` and I noticed that it can only spawn vehicle with role_name of 'ego_vehicle' 
I am using the `objects.json.template`
If I change the role_name to 'hero0', it will cause an error: 

> Traceback (most recent call last):
>   File "/home/pricejiang/carla-ros-bridge/catkin_ws/devel/lib/carla_spawn_objects/carla_spawn_objects.py", line 15, in <module>
>     exec(compile(fh.read(), python_script, 'exec'), context)
>   File "/home/pricejiang/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py", line 391, in <module>
>     main()
>   File "/home/pricejiang/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py", line 374, in main
>     spawn_objects_node.spawn_objects()
>   File "/home/pricejiang/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py", line 127, in spawn_objects
>     self.setup_vehicles(vehicles)
>   File "/home/pricejiang/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py", line 152, in setup_vehicles
>     spawn_point_param = self.get_param("spawn_point_" + vehicle["id"], None)
>   File "/home/pricejiang/carla-ros-bridge/catkin_ws/src/ros-bridge/ros_compatibility/src/ros_compatibility/ros_compatible_node.py", line 101, in get_param
>     return rospy.get_param("~" + name)
>   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 467, in get_param
>     return _param_server[param_name] #MasterProxy does all the magic for us
>   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 123, in __getitem__
>     raise KeyError(key)
> KeyError: '~spawn_point_hero0'
> [INFO] [1617143667.596356, 763.110993]: Destroying spawned objects...
> [INFO] [1617143667.750520, 0.000000]: Reconfigure Request:  speed (0.05, 0.0, 0.5), accel (0.02, 0.0, 0.05)
> [carla_spawn_objects_pricejiang_desktop_39607_5560597153345519092-1] process has died [pid 39622, exit code 1, cmd /home/pricejiang/carla-ros-bridge/catkin_ws/devel/lib/carla_spawn_objects/carla_spawn_objects.py __name:=carla_spawn_objects_pricejiang_desktop_39607_5560597153345519092 __log:=/home/pricejiang/.ros/log/0e8cc280-91a8-11eb-9cc4-81eb08b0f453/carla_spawn_objects_pricejiang_desktop_39607_5560597153345519092-1.log].
> log file: /home/pricejiang/.ros/log/0e8cc280-91a8-11eb-9cc4-81eb08b0f453/carla_spawn_objects_pricejiang_desktop_39607_5560597153345519092-1*.log

It seems like the use of `ros_compatibility` causes the problem. 
If I change the line 152 of `carla_spawn_objects.py` from `self.get_param` to `rospy.get_param`, the problem is fixed.

**Comment by AzaelCicero** [comment]
Hi @joel-mb, 
I you are using default launch files to spawn vehicle, then make sure that you change key of the setting from `spawn_point_ego_vehicle` to `spawn_point_hero0`

https://github.com/carla-simulator/ros-bridge/blob/e1a99d94eca9fa82c7bfb8417d2282ef6939d8fa/carla_spawn_objects/launch/carla_spawn_objects.launch.py#L35-L37
