### ISSUE TITLE
roslaunch pcl_recorder not saving or generating files in .pcd files in /tmp/pcl_recorder

### ISSUE THREAD

**Issue by kanakab** [carla-simulator/ros-bridge#520]
I have a custom map from Roadrunner and I need to generate the .pcd file to use this map in Autoware and carla. I am using the ros-bridge and the roslaunch pcl_recorder pcl_recorder.launch command to generate the files. The command launches the ros manual control and the vehicle is driving in both autopilot and manual mode but I don't see any pcd files generated. I have left the vehicle to run in autopilot for more than 45 min and used manual control but still I don't get any pcd files generated. I got couple of warnings like could not create directory and one error about tf.

Please help me fix this issue. Below is the output from the console:

... logging to /home/carissma-c301/.ros/log/ba549094-9797-11eb-8db4-a8a159388c12/roslaunch-carissmac301-9872.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://carissmac301:40161/

SUMMARY
========

PARAMETERS
 * /carla/ego_vehicle/role_name: ['hero', 'ego_veh...
 * /carla/fixed_delta_seconds: 0.05
 * /carla/host: localhost
 * /carla/passive: False
 * /carla/port: 2000
 * /carla/synchronous_mode: False
 * /carla/synchronous_mode_wait_for_vehicle_control_command: True
 * /carla/timeout: 10
 * /carla_manual_control_ego_vehicle/role_name: ego_vehicle
 * /carla_spawn_objects_carissmac301_9872_1349981719998387378/objects_definition_file: /home/carissma-c3...
 * /carla_spawn_objects_carissmac301_9872_1349981719998387378/spawn_point_ego_vehicle: 
 * /carla_spawn_objects_carissmac301_9872_1349981719998387378/spawn_sensors_only: False
 * /pcl_recorder_node/role_name: ego_vehicle
 * /rosbag_fname: 
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /set_initial_pose_ego_vehicle/control_id: control
 * /set_initial_pose_ego_vehicle/role_name: ego_vehicle
 * /use_sim_time: True

NODES
  /
    carla_manual_control_ego_vehicle (carla_manual_control/carla_manual_control.py)
    carla_ros_bridge (carla_ros_bridge/bridge.py)
    carla_spawn_objects_carissmac301_9872_1349981719998387378 (carla_spawn_objects/carla_spawn_objects.py)
    enable_autopilot_rostopic (rostopic/rostopic)
    pcl_recorder_node (pcl_recorder/pcl_recorder_node)
    set_initial_pose_ego_vehicle (carla_spawn_objects/set_initial_pose.py)

auto-starting new master
process[master]: started with pid [9883]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ba549094-9797-11eb-8db4-a8a159388c12
process[rosout-1]: started with pid [9894]
started core service [/rosout]
process[enable_autopilot_rostopic-2]: started with pid [9897]
process[pcl_recorder_node-3]: started with pid [9899]
process[carla_ros_bridge-4]: started with pid [9903]
process[carla_spawn_objects_carissmac301_9872_1349981719998387378-5]: started with pid [9904]
process[set_initial_pose_ego_vehicle-6]: started with pid [9905]
process[carla_manual_control_ego_vehicle-7]: started with pid [9906]
**[ WARN] [1617796349.357070765]: Could not create directory!**
pygame 2.0.1 (SDL 2.0.14, Python 2.7.17)
Hello from the pygame community. https://www.pygame.org/contribute.html
[INFO] [1617796350.892403, 0.000000]: Trying to connect to localhost:2000
[INFO] [1617796350.942465, 0.000000]: synchronous_mode: False
[INFO] [1617796350.943617, 0.000000]: fixed_delta_seconds: 0.05
WARNING: cannot parse georeference: ''. Using default values. 
WARNING: Traffic sign 2318 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2319 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2317 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2316 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2315 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2314 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2309 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2312 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2320 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2302 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2310 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2321 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2299 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2300 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2303 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2304 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2306 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2311 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2305 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
[INFO] [1617796351.132092, 0.000000]: Created TrafficLight(id=96)
[INFO] [1617796351.132930, 0.000000]: Created TrafficLight(id=97)
[INFO] [1617796351.133711, 0.000000]: Created TrafficLight(id=98)
[INFO] [1617796351.134501, 0.000000]: Created TrafficLight(id=99)
[INFO] [1617796351.135307, 0.000000]: Created TrafficLight(id=100)
[INFO] [1617796351.136033, 0.000000]: Created TrafficLight(id=101)
[INFO] [1617796351.136616, 0.000000]: Created TrafficLight(id=102)
[INFO] [1617796351.137187, 0.000000]: Created Spectator(id=86)
[INFO] [1617796351.137730, 0.000000]: Created TrafficLight(id=87)
[INFO] [1617796351.138324, 0.000000]: Created TrafficLight(id=88)
[INFO] [1617796351.138892, 0.000000]: Created TrafficLight(id=89)
[INFO] [1617796351.139434, 0.000000]: Created TrafficLight(id=90)
[INFO] [1617796351.139975, 0.000000]: Created TrafficLight(id=91)
[INFO] [1617796351.140522, 0.000000]: Created TrafficLight(id=92)
[INFO] [1617796351.141317, 0.000000]: Created TrafficLight(id=93)
[INFO] [1617796351.142082, 0.000000]: Created TrafficLight(id=94)
[INFO] [1617796351.142828, 0.000000]: Created TrafficLight(id=95)
[INFO] [1617796351.155280, 0.000000]: Created TrafficLightsSensor(id=10000)
[INFO] [1617796351.158916, 0.000000]: Created ObjectSensor(id=10001)
[INFO] [1617796351.161852, 0.000000]: Created ActorListSensor(id=10002)
[INFO] [1617796351.164926, 0.000000]: Created MarkerSensor(id=10003)
WARNING: cannot parse georeference: ''. Using default values. 
WARNING: Traffic sign 2318 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2319 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2317 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2316 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2315 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2314 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2309 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2312 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2320 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2302 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2310 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2321 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2299 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2300 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2303 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2304 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2306 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2311 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2305 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
[INFO] [1617796351.351561, 0.000000]: Created OpenDriveSensor(id=10004)
[WARN] [1617796351.352966, 0.000000]: Invalid spawnpoint ''
[WARN] [1617796351.353627, 0.000000]: ego_vehicle: Could not use spawn point from parameters, the spawn point from config file will be used.
[INFO] [1617796351.354505, 8.424931]: Spawn point selected at random
WARNING: cannot parse georeference: ''. Using default values. 
WARNING: Traffic sign 2318 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2319 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2317 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2316 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2315 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2314 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2309 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2312 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2320 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2302 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2310 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2321 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2299 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2300 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2303 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2304 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2306 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2311 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2305 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
[INFO] [1617796351.561818, 9.474931]: Created EgoVehicle(id=103)
[INFO] [1617796351.583917, 9.774931]: Created RgbCamera(id=104)
[INFO] [1617796351.966070, 10.024931]: Created RgbCamera(id=105)
WARNING: cannot parse georeference: ''. Using default values. 
[INFO] [1617796351.988660, 10.074931]: Created ActorControl(id=10005)
WARNING: Traffic sign 2318 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2319 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2317 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2316 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2315 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2314 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2309 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2312 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2320 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2302 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2310 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2321 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2299 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2300 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2303 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2304 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2306 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2311 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2305 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
[INFO] [1617796352.078602, 10.174931]: Created Lidar(id=106)
[INFO] [1617796352.168866, 10.274931]: Created SemanticLidar(id=107)
[INFO] [1617796352.281693, 10.374931]: Created Radar(id=108)
[INFO] [1617796352.388938, 10.474931]: Created SemanticSegmentationCamera(id=109)
[INFO] [1617796352.569163, 10.624931]: Created DepthCamera(id=110)
[INFO] [1617796352.694650, 10.724931]: Created DVSCamera(id=111)
[INFO] [1617796352.877310, 10.824931]: Created Gnss(id=112)
[INFO] [1617796353.101491, 10.974931]: Created ImuSensor(id=113)
[INFO] [1617796353.361483, 11.074931]: Created CollisionSensor(id=114)
WARNING: cannot parse georeference: ''. Using default values. 
WARNING: Traffic sign 2318 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2319 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2317 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2316 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2315 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2314 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2309 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2312 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2320 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2302 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2310 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2321 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2299 overlaps a driving lane. Moving out of the road... 
WARNING: Traffic sign 2300 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2303 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2304 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2306 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2311 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
WARNING: Traffic sign 2305 overlaps a driving lane. Moving out of the road... 
WARNING: Failed to find suitable place for signal. 
[INFO] [1617796353.879945, 11.224931]: Created LaneInvasionSensor(id=115)
[INFO] [1617796353.917323, 11.374931]: Created TFSensor(id=10006)
[INFO] [1617796353.949819, 11.374931]: Created ObjectSensor(id=10007)
[INFO] [1617796353.994061, 11.424931]: Created OdometrySensor(id=10008)
[INFO] [1617796353.996808, 11.424931]: Created SpeedometerSensor(id=10009)
[INFO] [1617796354.106232, 11.474931]: Created ActorControl(id=10010)
[WARN] [1617797620.761358, 864.374944]: Update actor ObjectSensor(10001) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.763911, 864.374944]: Update actor MarkerSensor(10003) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.765010, 864.374944]: Update actor TFSensor(10006) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.766588, 864.374944]: Update actor OdometrySensor(10008) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.769447, 864.374944]: Update actor SpeedometerSensor(10009) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.770216, 864.374944]: Update actor EgoVehicle(103) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.796269, 864.424944]: Update actor ObjectSensor(10001) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.799833, 864.424944]: Update actor MarkerSensor(10003) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.815180, 864.424944]: Update actor TFSensor(10006) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.816634, 864.424944]: Update actor OdometrySensor(10008) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.817632, 864.424944]: Update actor SpeedometerSensor(10009) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[WARN] [1617797620.818627, 864.424944]: Update actor EgoVehicle(103) failed: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
[INFO] [1617797620.824070, 864.424944]: Removed EgoVehicle(id=103)
Traceback (most recent call last):
  File "/home/carissma-c301/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 342, in _carla_time_tick
    carla_snapshot.timestamp.elapsed_seconds)
  File "/home/carissma-c301/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 377, in _update
    self.actor_factory.actors[actor_id].update(frame_id, timestamp)
  File "/home/carissma-c301/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/tf_sensor.py", line 58, in update
    pose = self.parent.get_current_ros_pose()
  File "/home/carissma-c301/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/actor.py", line 65, in get_current_ros_pose
    self.carla_actor.get_transform())
AttributeError: 'NoneType' object has no attribute 'get_transform'
[WARN] [1617797627.023829, 864.474944]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[WARN] [1617797627.049791, 864.474944]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[WARN] [1617797627.050901, 864.474944]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[carla_manual_control_ego_vehicle-7] process has finished cleanly
log file: /home/carissma-c301/.ros/log/ba549094-9797-11eb-8db4-a8a159388c12/carla_manual_control_ego_vehicle-7*.log
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/carissma-c301/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/actor_factory.py", line 81, in _update_thread
    self.world.wait_for_tick()
RuntimeError: time-out of 10000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000

^C[set_initial_pose_ego_vehicle-6] killing on exit
[carla_spawn_objects_carissmac301_9872_1349981719998387378-5] killing on exit
[carla_ros_bridge-4] killing on exit
[pcl_recorder_node-3] killing on exit
[enable_autopilot_rostopic-2] killing on exit
[INFO] [1617798437.483672, 864.474944]: Shutdown requested
ERROR: failed to destroy actor 104 : time-out of 10000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000 
[carla_spawn_objects_carissmac301_9872_1349981719998387378-5] escalating to SIGTERM
[carla_ros_bridge-4] escalating to SIGTERM
[WARN] [1617798452.389980, 864.474944]: transport error completing service call: receive_once[/carla/destroy_object]: unexpected error [Errno 4] Interrupted system call
[carla_ros_bridge-4] escalating to SIGKILL
[carla_spawn_objects_carissmac301_9872_1349981719998387378-5] escalating to SIGKILL
[rosout-1] killing on exit
[master] killing on exit
Shutdown errors:
 * process[carla_spawn_objects_carissmac301_9872_1349981719998387378-5, pid 9904]: required SIGKILL. May still be running.
 * process[carla_ros_bridge-4, pid 9903]: required SIGKILL. May still be running.
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by joel-mb** [comment]
closing issue as this was solved in Discord.
