### ISSUE TITLE
Carl installation problems

### ISSUE THREAD

**Issue by rrun1** [carla-simulator/ros-bridge#53]
Hi, 

I have installed the egg and the installation seems successful and when I run python spawn command I am getting an ImportError. Please help. 

----------------------------------------
xdsim@prescan2:~/carla_0_9_2$ sudo easy_install /home/xdsim/carla_0_9_2/PythonAPI/carla-0.9.2-py3.5-linux-x86_64.egg
Processing carla-0.9.2-py3.5-linux-x86_64.egg
removing '/usr/local/lib/python3.5/dist-packages/carla-0.9.2-py3.5-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python3.5/dist-packages/carla-0.9.2-py3.5-linux-x86_64.egg
Extracting carla-0.9.2-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/dist-packages
carla 0.9.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.5/dist-packages/carla-0.9.2-py3.5-linux-x86_64.egg
Processing dependencies for carla==0.9.2
Finished processing dependencies for carla==0.9.2
xdsim@prescan2:~/carla_0_9_2$ 
------------------------------------------------------------

xdsim@prescan2:~/carla_0_9_2$ python3 spawn_npc.py -n 80
Traceback (most recent call last):
  File "spawn_npc.py", line 23, in <module>
    import carla
  File "/usr/local/lib/python3.5/dist-packages/carla-0.9.2-py3.5-linux-x86_64.egg/carla/__init__.py", line 7, in <module>
    from .libcarla import *
ImportError: libpng16.so.16: cannot open shared object file: No such file or directory
xdsim@prescan2:~/carla_0_9_2$ 
--------------------------------------------------------------

**Comment by mallela** [comment]
Instead of using easy_install try :
`
$ export PYTHONPATH=$PYTHONPATH:<path_to_egg_file>
$ python -c 'import carla;print("Success")'
`
The last command must print Success if carla has been successfully imported.
