### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_weak_ptr'

### ISSUE THREAD

**Issue by zlw21gxy** [carla-simulator/ros-bridge#59]
![image](https://user-images.githubusercontent.com/46110602/54472867-d318c700-480a-11e9-8caa-fe74ef97f391.png)
hey guys, I am using Carla 0.9.4 and Ubuntu 16.04
does anyone why this error happen? thanks!!!!
I guess it's due to listening to sensor

**Comment by togaen** [comment]
I think that is possibly the same as this issue #24

**Comment by fpasch** [comment]
Should be fixed with 0.9.10
