### ISSUE TITLE
ROS2 failed to build carla_ad_demo

### ISSUE THREAD

**Issue by gunnxx** [carla-simulator/ros-bridge#611]
The error is
```
--- stderr: carla_ad_demo                          
error: Multiple top-level packages discovered in a flat-layout: ['launch', 'config', 'resource'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
```

I am using `carla-simulator=0.9.12`, `ros2 foxy`, and `setuptools=62.0.0`. Anyone having the same issue? I am not familiar with ros2 commands such as colcon build.

**Comment by joe28965** [comment]
Yes, got it just now. Have you been able to resolve it?

**Comment by gunnxx** [comment]
I switched to `ros1 noetic` lmao.

**Comment by joe28965** [comment]
Thanks, not going to work for me I'm afraid. Will try some stuff myself

**Comment by joe28965** [comment]
Fixed it btw, will create a PR for it, if you're still interested

**Comment by muddassir93** [comment]
> The error is
> 
> ```
> --- stderr: carla_ad_demo                          
> error: Multiple top-level packages discovered in a flat-layout: ['launch', 'config', 'resource'].
> 
> To avoid accidental inclusion of unwanted files or directories,
> setuptools will not proceed with this build.
> 
> If you are trying to create a single distribution with multiple packages
> on purpose, you should not rely on automatic discovery.
> Instead, consider the following options:
> 
> 1. set up custom discovery (`find` directive with `include` or `exclude`)
> 2. use a `src-layout`
> 3. explicitly set `py_modules` or `packages` with a list of names
> 
> To find more information, look for "package discovery" on setuptools docs.
> ```
> 
> I am using `carla-simulator=0.9.12`, `ros2 foxy`, and `setuptools=62.0.0`. Anyone having the same issue? I am not familiar with ros2 commands such as colcon build.

This query is old and has been resolved. I am commenting for future reference.

This issue `error: Multiple top-level packages discovered in a flat-layout: ['share', 'resource'].` can be resolved if `packages=[]` is passed in `setup(...)`.

I got into this issue and resolved it with the above solution in `setuptools==68.1.2` and ros `humble`
