### ISSUE TITLE
Error when trying to use carla_msgs 

### ISSUE THREAD

**Issue by torpedlars** [carla-simulator/ros-bridge#690]
Hello! 
I'm struggling a bit with using the carla ros bridge in ROS2. I have a node that is reading the velocity from carla, it's reading the message CarlaEgoVehicleStatus.
I've added <(depend> carla_msgs </depend)> (without the parenthesis) to the package.xml file and also find_package(carla_msgs REQUIRED) to the CMakeLists.txt.
It gives me the error:
fatal error: carla_msgs/msg/CarlaEgoVehicleStatus.hpp: No such file or directory 12 | #include "carla_msgs/msg/CarlaEgoVehicleStatus.hpp"
I've tried with snake case on the include line without any luck.

Can anyone point me in the right direction of where i'm going wrong because i dont really understand why it doesn't find the msg. 
I can see the package and messages when i run: ros2 interface list / ros2 interface show etc.

Friendly regards
Marcus

**Comment by johnren-code** [comment]
Hello, have you solved it? Any solutions?
