### ISSUE TITLE
Links to wrong Ros bridge

### ISSUE THREAD

**Issue by rrun1** [carla-simulator/ros-bridge#73]
HI, 

I am trying to send the image saved from my camera (using our existing programs in Carla environment) on the ego vehicle across to ROS environment. 

1) How can I include that in my python code ? 

2) When I try to run roslaunch command - 
_roslaunch carla_ros_bridge carla_ros_bridge.launch_

roslaunch  is trying to access a previously built ros brige.. How do I point It to the newly built ros bridge ? 

I am using Carla 0.9.2 and ROS Lunar

"/home/xds/catkin_ws/src/carla_ros_bridge1/src/carla_ros_bridge/client.py" from the error message listed below is the wrong path. 

Correct path should be -
"/home/xds/ros/carla_ros_bridge/src/carla_ros_bridge/client.py" which is the client.py from the new Carla bridge. How do I correct the link ? 

My paths - 
Path to Carla is - /home/xds/Carla_0_9_2/
Path to ros bridge - /home/xds/ros/Carla_ros_bridge/
Path to catkin workspace  where my ros program is - /home/xds/catkin_ws_carla/

Any ideas please ! 

Thanks, 
-----------------------------------------------------------------------------------

xds@prescan2:~/ros/catkin_ws_carla$ roslaunch carla_ros_bridge client.launch
WARNING: Package name "ClosedLoopRealtime" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "WMGCarmakerCameraRSI" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "ClosedLoopRealtimeACSToPod" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
... logging to /home/xds/.ros/log/b098ecea-41c1-11e9-ad39-246e964d427a/roslaunch-prescan2-14824.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

WARNING: Package name "ClosedLoopRealtime" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "WMGCarmakerCameraRSI" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "ClosedLoopRealtimeACSToPod" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
started roslaunch server http://prescan2:36485/

SUMMARY
========

PARAMETERS
 * /carla/Episodes: 2
 * /carla/Framesperepisode: -1
 * /carla/NumberOfPedestrians: 10
 * /carla/NumberOfVehicles: 30
 * /carla/QualityLevel: Low
 * /carla/SendNonPlayerAgentsInfo: True
 * /carla/SynchronousMode: True
 * /carla/WeatherId: 1
 * /carla/host: localhost
 * /carla/port: 2000
 * /carla/sensors/camera_depth/SensorType: CAMERA
 * /carla/sensors/camera_depth/carla_settings/FOV: 90
 * /carla/sensors/camera_depth/carla_settings/ImageSizeX: 320
 * /carla/sensors/camera_depth/carla_settings/ImageSizeY: 240
 * /carla/sensors/camera_depth/carla_settings/PositionX: 1.8
 * /carla/sensors/camera_depth/carla_settings/PositionY: 0
 * /carla/sensors/camera_depth/carla_settings/PositionZ: 1.3
 * /carla/sensors/camera_depth/carla_settings/PostProcessing: Depth
 * /carla/sensors/camera_depth/carla_settings/RotationPitch: 0
 * /carla/sensors/camera_depth/carla_settings/RotationRoll: 0
 * /carla/sensors/camera_depth/carla_settings/RotationYaw: 0
 * /carla/sensors/camera_front/SensorType: CAMERA
 * /carla/sensors/camera_front/carla_settings/FOV: 90
 * /carla/sensors/camera_front/carla_settings/ImageSizeX: 320
 * /carla/sensors/camera_front/carla_settings/ImageSizeY: 240
 * /carla/sensors/camera_front/carla_settings/PositionX: 1.8
 * /carla/sensors/camera_front/carla_settings/PositionY: 0
 * /carla/sensors/camera_front/carla_settings/PositionZ: 1.3
 * /carla/sensors/camera_front/carla_settings/PostProcessing: SceneFinal
 * /carla/sensors/camera_front/carla_settings/RotationPitch: 0
 * /carla/sensors/camera_front/carla_settings/RotationRoll: 0
 * /carla/sensors/camera_front/carla_settings/RotationYaw: 0
 * /carla_autopilot: True
 * /curr_episode: 
 * /rosbag_fname: 
 * /rosdistro: lunar
 * /rosversion: 1.13.7

NODES
  /
    carla_ros_bridge (carla_ros_bridge/client.py)

ROS_MASTER_URI=http://localhost:11311

WARNING: Package name "ClosedLoopRealtime" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "WMGCarmakerCameraRSI" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "ClosedLoopRealtimeACSToPod" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[carla_ros_bridge-1]: started with pid [14841]
Traceback (most recent call last):
  File "/home/xds/catkin_ws/src/carla_ros_bridge1/src/carla_ros_bridge/client.py", line 8, in <module>
    from carla.client import make_carla_client
  File "/home/xds/carla_0_9_2/PythonAPI/carla-0.9.2-py3.5-linux-x86_64.egg/carla/__init__.py", line 7, in <module>
    
  File "/home/xds/carla_0_9_2/PythonAPI/carla-0.9.2-py3.5-linux-x86_64.egg/carla/libcarla.py", line 7, in <module>
  File "/home/xds/carla_0_9_2/PythonAPI/carla-0.9.2-py3.5-linux-x86_64.egg/carla/libcarla.py", line 6, in __bootstrap__
ImportError: /home/xds/.cache/Python-Eggs/carla-0.9.2-py3.5-linux-x86_64.egg-tmp/carla/libcarla.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyUnicode_AsUTF8String
[carla_ros_bridge-1] process has died [pid 14841, exit code 1, cmd /home/xds/catkin_ws/src/carla_ros_bridge1/src/carla_ros_bridge/client.py __name:=carla_ros_bridge __log:=/home/xds/.ros/log/b098ecea-41c1-11e9-ad39-246e964d427a/carla_ros_bridge-1.log].
log file: /home/xds/.ros/log/b098ecea-41c1-11e9-ad39-246e964dxds@prescan2:~$ rostopic pub /carla/ego_vehicle_cmd carla_ros_bridge/CarlaEgoVehicleControl "{throttle; 1.0, steer: 0.0}" -r 10
The program 'rostopic' is currently not installed. You can install it by typing:
sudo apt install python-rostopic

**Comment by fpasch** [comment]
Latest ros bridge is not compatible with Carla 0.9.2. 
Current master of ros-bridge works together with the master of Carla. So either you build Carla yourself, our you have to wait until the next release of Carla 0.9.5.
