### ISSUE TITLE
Import Error with agents package [carla_waypoint_publisher]

### ISSUE THREAD

**Issue by SIlvaMFPedro** [carla-simulator/ros-bridge#92]
Good evening. I installed the "agents" package with the command:
 - sudo pip install agents
But for some reason my Pycharm says that this package does not have a navigation folder.
![import_agents_error](https://user-images.githubusercontent.com/22821533/55646399-02e83880-57d3-11e9-9b8a-58f5f1fcdd3b.png)

Did i install the right package? Or do i have to installed the package some other way?

Thank you

Pedro Silva - 72645

**Comment by SIlvaMFPedro** [comment]
Nevermind. I figured it out.

**Comment by vehxianfish** [comment]
Hi,I also meet this question,not find any solution.Can you tell me how to solve this question?thank you.

**Comment by jishenghuang** [comment]
I encountered the same problem. How did you solve it?
