### ISSUE TITLE
frame_id for VehicleStatus message is empty

### ISSUE THREAD

**Issue by togaen** [carla-simulator/ros-bridge#99]
The `frame_id` field is not populated in the header for the `VehicleStatus` message published by the bridge. I assume it should be `/map`. Is that the case?

**Comment by togaen** [comment]
I am also curious: What is the utility of have velocity/acceleration/orientation in the vehicle status message? Isn't all of that information provided by the odometry message?

**Comment by togaen** [comment]
I also assume that the orientation is specified with respect to the x axis?

**Comment by fpasch** [comment]
Hi togaen. I was planning to remove the orientation from VehicleStatus, as it is already published via odometry-message. Do you really require it?

**Comment by togaen** [comment]
@fpasch No, that would be perfect.
